intradastingly/fashion-store-backend

- client/src/componenets/Cart/CompleteOrder.tsx
- client/src/componenets/Cart/InformationForm.tsx
- client/src/componenets/OrderSuccess/Reciept.tsx
- client/src/componenets/User/logIn.tsx
- client/src/contexts/CartContext.tsx
- server/resources/order/controller.ts
- server/resources/order/model.ts
- server/resources/order/order.rest
- server/resources/order/router.ts
- server/resources/product/model.ts
Username and password info from login.tsx in client to context
> Order refs

- client/src/App.tsx
- client/src/componenets/ProductDetails/ProductDetails.tsx
- client/src/componenets/StartPage/ProductCardGrid.tsx
- client/src/componenets/User/logIn.tsx
- client/src/contexts/ApiContext.tsx
API context has it's own file using hooks(better)
> api context

- client/src/App.tsx
- client/src/componenets/Cart/CartItemsList.tsx
- client/src/componenets/ProductDetails/ProductDetails.tsx
- client/src/componenets/StartPage/ProductCardGrid.tsx
- client/src/contexts/CartContext.tsx
Cart is updated from API products
> Api context to cart context

- client/src/componenets/StartPage/ProductCardGrid.tsx
- client/src/contexts/ApiContext.tsx
- client/src/contexts/CartContext.tsx
- server/app.ts
- server/resources/guest/controller.ts
- server/resources/guest/guest.rest
- server/resources/guest/model.ts
- server/resources/guest/router.ts
- server/resources/login/controller.ts
- server/resources/login/login.rest
cart working to add and remove products on front end. 
API gets receipt value for further use. 
new guest API end point for page load
> Get data from order confirm to backend

- client/src/componenets/Cart/CompleteOrder.tsx
- client/src/componenets/Cart/DeliverySelection.tsx
- client/src/componenets/deliveryMethods.ts
- client/src/contexts/ApiContext.tsx
- client/src/contexts/CartContext.tsx
- server/resources/shipping/controller.ts
- server/resources/shipping/model.ts
- server/resources/shipping/shipping.rest
Reverts intradastingly/fashion-store-backend#74
> Revert "Shippingmethod"

- client/src/componenets/OrderSuccess/Reciept.tsx
- client/src/componenets/User/logIn.tsx
- client/src/contexts/ApiContext.tsx
- client/src/contexts/CartContext.tsx
- server/resources/order/controller.ts
> Session id in order

- client/src/contexts/ApiContext.tsx
- client/src/contexts/CartContext.tsx
- server/resources/order/controller.ts
- server/resources/order/model.ts
order model schema from front end
> Order model

- client/src/contexts/ApiContext.tsx
- server/resources/login/controller.ts
- server/resources/order/controller.ts
- server/resources/order/model.ts
some product code in product controller
> Why no worrrk

- server/resources/account/model.ts
- server/resources/order/controller.ts
- server/resources/order/model.ts
- server/resources/product/model.ts
- server/resources/shipping/model.ts
> Volume changes on order quantity  

- server/resources/order/controller.ts
- server/resources/order/model.ts
- server/resources/product/model.ts
quantity subtracted from database
> product subtractor takes from the product databsase

- client/src/componenets/StartPage/ProductCardGrid.tsx
> Front end catgeories

- client/src/componenets/StartPage/ProductCardGrid.tsx
works to sort based on categories. not 100 working yet
> works to sort products based on category

- client/src/componenets/Admin/AddNewProduct.tsx
- client/src/componenets/Admin/AdminEditDetails.tsx
- client/src/componenets/StartPage/ProductCardGrid.tsx
- server/resources/product/controller.ts
> New branch hurrah!

- client/src/componenets/Cart/CartView.tsx
If cart empty nothing in cart page
> nothing in cart

- client/src/componenets/Cart/CartView.tsx
- server/resources/product/controller.ts
products have "All' added when created on editProduct controller
> Products have All category when edited now

- client/src/componenets/StartPage/ProductCardGrid.tsx
- client/src/windowSize.tsx
- server/resources/order/controller.ts
- server/resources/product/product.rest
Fucntion for window width and height
mobile categories vieqw
> Window width height

- client/src/App.tsx
- client/src/componenets/Admin/AddNewUser.tsx
- client/src/componenets/Admin/AdminUsers.tsx
- client/src/contexts/ApiContext.tsx
- server/resources/account/controller.ts
Co-authored-by: lilgujj <gustavkarlandersson@hotmail.com>
> add new user on adminpage logic done

- client/src/componenets/Admin/AddNewProduct.tsx
- client/src/contexts/ApiContext.tsx
Co-authored-by: lilgujj <gustavkarlandersson@hotmail.com>
> required fields for add new product done

- client/src/componenets/Admin/AddNewUser.tsx
- client/src/componenets/Cart/CartView.tsx
Co-authored-by: lilgujj <gustavkarlandersson@hotmail.com>
> styling update

- client/src/componenets/Admin/EditUsers.tsx
Co-authored-by: lilgujj <gustavkarlandersson@hotmail.com>
> add edit password, admin users
